### ISSUE TITLE
plugin niet geïnitialiseerd

### ISSUE THREAD

**Issue by Theo-denBlanken** [EdgeworthWright/jquery-opdracht#2]
Je hebt feedback gekregen van **Theo-denBlanken**
URL: https://github.com/EdgeworthWright/jquery-opdracht/blob/master/

Feedback: er is geen slider te ontdekken[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/ '#cr:{"reviewer":"Theo-denBlanken"}')

**Comment by EdgeworthWright** [comment]
De plugin staat op deze pagina: http://25890.hosts2.ma-cloud.nl/bewijzenmap/periode1.4/fro/jquery/opdracht.html

het is een carousel
